In [107]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error
import math

# 1 Read Traning Data

## 1.1 Read X

In [29]:
df_Xt = pd.read_csv('data/trainData.csv', header=None)
del df_Xt[0]
df_Xt['3001'] = 1

In [45]:
df_Xt.describe()

1            2            3            4            5  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean      0.000117     0.000592     0.000358     0.000778     0.002907   
std       0.004773     0.010521     0.009350     0.012686     0.023443   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       0.209000     0.250000     0.378000     0.267000     0.267000   

                 6            7            8            9           10  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean      0.002169     0.000371     0.000711     0.000423     0.003197   
std       0.020401     0.008833     0.011637     0.009116     0.025986   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       0.256000     0.267000     0.243000     0.243000     0.365000   

        ...           2992         2993         2994         2995  \
count   ...    5000.000000  5000.000000  5000.000000  5000.000000   
mean    ...       0.000837     0.001868     0.002873     0.000988   
std     ...       0.012444     0.018735     0.024009     0.014105   
min     ...       0.000000     0.000000     0.000000     0.000000   
25%     ...       0.000000     0.000000     0.000000     0.000000   
50%     ...       0.000000     0.000000     0.000000     0.000000   
75%     ...       0.000000     0.000000     0.000000     0.000000   
max     ...       0.236000     0.243000     0.302000     0.267000   

              2996         2997         2998         2999         3000    3001  
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000  5000.0  
mean      0.005224     0.004936     0.000440     0.000591     0.000395     1.0  
std       0.034376     0.031370     0.009485     0.011273     0.008894     0.0  
min       0.000000     0.000000     0.000000     0.000000     0.000000     1.0  
25%       0.000000     0.000000     0.000000     0.000000     0.000000     1.0  
50%       0.000000     0.000000     0.000000     0.000000     0.000000     1.0  
75%       0.000000     0.000000     0.000000     0.000000     0.000000     1.0  
max       0.474000     0.348000     0.258000     0.267000     0.250000     1.0  

[8 rows x 3001 columns]

In [46]:
df_Xt

1    2    3    4      5    6    7    8    9   10  ...   2992   2993  \
0     0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
1     0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
2     0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
3     0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4     0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
5     0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
6     0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
7     0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
8     0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
9     0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
10    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
11    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
12    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
13    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
14    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
15    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
16    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
17    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
18    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
19    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
20    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
21    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
22    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
23    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
24    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
25    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
26    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
27    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
28    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
29    0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
...   ...  ...  ...  ...    ...  ...  ...  ...  ...  ...  ...    ...    ...   
4970  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4971  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4972  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4973  0.2  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4974  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4975  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4976  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4977  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4978  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4979  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4980  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4981  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.218   
4982  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4983  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4984  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4985  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4986  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4987  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000   
4988  0.0  0.0  0.0  0.0  0.000  0.0  0.0  0.0  0.0  0.0  

In [47]:
Xt = df_Xt.values
Xt.shape

(5000, 3001)

In [48]:
X = Xt.transpose()
X.shape

(3001, 5000)

## 1.2 Read y

In [39]:
df_y = pd.read_csv('data/trainLabels.csv', header=None)
del df_y[0]

In [40]:
df_y.describe()

1
count  5000.000000
mean     87.910800
std       3.393928
min      80.000000
25%      85.000000
50%      88.000000
75%      90.000000
max      99.000000

In [41]:
df_y

1
0     85
1     92
2     86
3     87
4     88
5     93
6     90
7     92
8     87
9     84
10    96
11    84
12    92
13    96
14    84
15    90
16    91
17    84
18    84
19    90
20    90
21    93
22    91
23    92
24    92
25    86
26    85
27    88
28    86
29    88
...   ..
4970  88
4971  89
4972  89
4973  91
4974  84
4975  91
4976  88
4977  89
4978  87
4979  89
4980  90
4981  90
4982  85
4983  84
4984  90
4985  84
4986  90
4987  94
4988  84
4989  87
4990  93
4991  92
4992  84
4993  93
4994  83
4995  86
4996  83
4997  88
4998  93
4999  86

[5000 rows x 1 columns]

In [43]:
y = df_y.values
y.shape

(5000, 1)

## 1.3 Summary

In [117]:
df_Xt = pd.read_csv('data/trainData.csv', header=None)
df_Xt[str(len(df_Xt.columns))] = 1
del df_Xt[0]
Xt = df_Xt.values
X = Xt.transpose()

df_y = pd.read_csv('data/trainLabels.csv', header=None)
del df_y[0]
y = df_y.values

# 2 Data Cleaning etc

# 3 Model - Ridge Algorithm

In [118]:
lambdaa = .1  # default \lambda

In [119]:
dimension = X.shape[0]

In [120]:
I = np.zeros((dimension, dimension))
for i in range(dimension):
    I[i, i] = 1

In [121]:
I*lambdaa

array([[ 0.1,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0.1,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.1, ...,  0. ,  0. ,  0. ],
       ..., 
       [ 0. ,  0. ,  0. , ...,  0.1,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0.1,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0.1]])

In [122]:
%time w_bar = np.linalg.inv(X@Xt + lambdaa*I) @ X @ y   # training the parameters

CPU times: user 8.09 s, sys: 183 ms, total: 8.28 s
Wall time: 2.75 s


In [123]:
w_bar.shape

(3001, 1)

In [124]:
w_bar

array([[  1.37033295],
       [  4.06053774],
       [  1.9151613 ],
       ..., 
       [ -1.11249553],
       [  2.09171501],
       [ 81.7300503 ]])

In [125]:
w = w_bar[0:dimension-1]
w.shape

(3000, 1)

In [126]:
b = w_bar[dimension-1]  # bias
b[0]

81.730050297404148

# 4 Predict

In [97]:
df_Xt = pd.read_csv('data/valData.csv', header=None)
del df_Xt[0]
df_Xt['3001'] = 1  # TODO: change to len()
Xt = df_Xt.values
X = Xt.transpose()

df_y = pd.read_csv('data/valLabels.csv', header=None)
del df_y[0]
y = df_y.values

In [99]:
Xt.shape

(5000, 3001)

In [101]:
w_bar.shape

(3001, 1)

In [105]:
pred = Xt @ w_bar
pred

array([[ 88.72282297],
       [ 89.37157627],
       [ 84.23986104],
       ..., 
       [ 89.97981095],
       [ 84.21474391],
       [ 93.35687387]])

In [106]:
y

array([[88],
       [91],
       [84],
       ..., 
       [90],
       [87],
       [93]])

In [108]:
def rmse(true, pred):
    '''Comupte the root mean squared error (RMSE)
    Parameter:
        true (np.ndarray, n = 1): ground truth
        pred (np.ndarray, n = 1): prediction
    '''
    return math.sqrt(mean_squared_error(true, pred))

In [109]:
rmse(y, pred)

2.155742390744341

In [144]:
np.linalg.norm(w)

143.89043331579097

In [155]:
def mynorm(w):
    summation = 0
    for i in w:
        summation += i**2
    return math.sqrt(summation)

print(mynorm(w))

143.89043331579123


In [156]:
%time np.linalg.norm(w)
%time mynorm(w)

CPU times: user 50 µs, sys: 12 µs, total: 62 µs
Wall time: 65.8 µs
CPU times: user 7.65 ms, sys: 84 µs, total: 7.73 ms
Wall time: 7.74 ms


143.89043331579123

In [174]:
w_bar

array([[  1.37033295],
       [  4.06053774],
       [  1.9151613 ],
       ..., 
       [ -1.11249553],
       [  2.09171501],
       [ 81.7300503 ]])

In [160]:
w_bar.transpose()

array([[  1.37033295,   4.06053774,   1.9151613 , ...,  -1.11249553,
          2.09171501,  81.7300503 ]])

In [162]:
X.shape

(3001, 5000)

In [172]:
xi = X[:, 1]
xi

array([ 0.,  0.,  0., ...,  0.,  0.,  1.])

In [173]:
xi.transpose()

array([ 0.,  0.,  0., ...,  0.,  0.,  1.])

---

---

# 5 Put Everything in a Class

In [175]:
class RidgeRegression:
    '''Caitao's implementation of Ridge Regression
    Attributes:
        w_bar (np.ndarray): w_bar = [w;1], shape=(k+1, 1)
    '''
    def __init__(self):
        w_bar = np.zeros(0)

        
    def read_X(self, filename):
        '''Read the feature data, and make it into desired shape
        Parameters:
            filename (str)
        Return:
            X  (np.ndarray): shape=(k+1, n)
        '''
        df_Xt = pd.read_csv(filename, header=None)
        df_Xt[str(len(df_Xt.columns))] = 1     # add one to each x_i
        del df_Xt[0]
        Xt = df_Xt.values
        X = Xt.transpose()
        return X
    
    
    def read_y(self, filename):
        '''Read the label data, and make it into desired shape
        Parameters:
            filename (str)
        Return:
            y  (np.ndarray): shape=(n, 1)
        '''
        df_y = pd.read_csv(filename, header=None)
        del df_y[0]
        return df_y.values
    
    
    def ridgeReg(self, X, y, lambdaa):
        '''Ridge regression. Trian the weights
        Parameters:
            X (np.ndarray):  feature data, shape=(k+1, n)
            y (np.ndarray):  label data, shape=(n, 1)
            lambdaa (float): the hyperparameter of ridge regression
        Return:
            w (np.ndarray):      trained weights, shape=(k, 1)
            b (float):           bias
            obj (float):         the value of the objective function
            cvErrs (np.ndarray): LOOCV errors, shape=(n, 1)
        '''
        dimension  = X.shape[0]
        num_sample = X.shape[1]
        
        I = np.zeros((dimension, dimension))
        for i in range(dimension):
            I[i, i] = 1
        
        Xt = X.transpose()
        
        C_in = np.linalg.inv(X@Xt + lambdaa*I)  # C^{-1} in the homework 2
        self.w_bar = C_in @ X @ y  # train the parameters
        
        w = self.w_bar[0:dimension-1]
        b = self.w_bar[dimension-1]
        pred = Xt @ self.w_bar
        obj = lambdaa*np.linalg.norm(w)**2 + np.linalg.norm(pred-y)**2
        loocv = []
        for i in range(num_sample):
            xi = X[:, i]
            error = (self.w_bar.transpose() @ xi - y[i]) / (1 - xi.transpose() @ C_in @ xi)
            loocv.append(error)
        
        return w, b, obj, np.array(loocv)
    
    
    def predict(self, X):
        '''Predict by using the trained self.w_bar
        Parameters:
            X (np.ndarray): shape=(k+1, n)
        Return:
            y (np.ndarray): shape=(n, 1)
        '''
        Xt = X.transpose()
        return Xt @ self.w_bar
    
    
    def rmse(true, pred):
        '''Comupte the root mean squared error (RMSE)
        Parameter:
            true (np.ndarray, n = 1): ground truth
            pred (np.ndarray, n = 1): prediction
        Return:
            rmse (float)
        '''
        return math.sqrt(mean_squared_error(true, pred))